### ISSUE TITLE
Can't find homebrew_info.json

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/homebrew_info#3]
`homebrew_info.sh Error: /usr/local/munkireport/scripts/homebrew_info.sh: line 45: /cache/homebrew_info.json: No such file or directory
`

v1.5 on multiple devices

**Comment by tuxudo** [comment]
Your homebrew instance is not configured correctly. Verify that you can run `brew config` on that Mac.

**Comment by jby** [comment]
I can run `brew config` and still get this error.
On line 44 of the script you use $DIR to set the path for the `homebrewfile`, however the `DIR` variable is never set before that...
https://github.com/munkireport/homebrew_info/blob/d7b099b3bb5a12422894f56f3a09db515823bc4b/scripts/homebrew_info.sh#L44-L45

The file is in `/usr/local/munkireport/scripts/cache/homebrew_info.json`, which would indicate that DIR ought to be `/usr/local/munkireport/scripts`

**Comment by tuxudo** [comment]
Fixed with version v1.6
